env:
  browser: false
  commonjs: true
  es2021: true
  node: true
  jest: true
extends: [ 'eslint:recommended',  'plugin:@typescript-eslint/eslint-recommended', 'plugin:@typescript-eslint/recommended' ]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins: [ "@typescript-eslint" ]
