/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:c7cfa399-7413-42af-901d-e1441fb4d916",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_Dyonw6Z16",
    "aws_user_pools_web_client_id": "3mp6tl8rmrporggpvtlelqvlv5",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://zo6s6vxvyrcgjhi7wkthegquvq.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-eyy7jjybd5bfdj4oputk3tmgwu",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};


module.exports.default = awsmobile;
